---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: Make sure www is running on Fedora
    tags: fedora
    ansible.builtin.service:
      name: httpd
      state: started
    when: ansible_distribution == "Fedora"

