---
- hosts: all
  become: true
  tasks:

  - name: Install updates for Fedora
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: Install updates on Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: Install apache on web servers
    tags: apache,ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"
  - name: Copy HTML file
    tags: apache,ubuntu
    ansible.builtin.copy:
      src: files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 644

  - name: Change admin email
    tags: fedora
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@acme.org
    when: ansible_distribution == "Fedora"
    register: httpd
#register is good for storing events, name can be anything

  - name: Restart httpd
    tags: fedora,apache
    ansible.builtin.service:
      name: httpd
      state: restarted
    when: httpd.change
# Here we are using the httpd register

- hosts: other_servers
  become: true
  tasks:
  - name: Install mariadb on other servers
    tags: db,fedora
    ansible.builtin.dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"

