---
- hosts: all
  become: true
  tasks:

  - name: Install updates for Fedora
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: Install updates on Ubuntu
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: Install apache on web servers
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

- hosts: other_servers
  become: true
  tasks:
  - name: Install mariadb on other servers
    ansible.builtin.dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"

